format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$golang\
$rust\
$character"""

[aws]
disabled = true

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[directory]
style = "bold bright-blue"

[git_branch]
format = "[$branch]($style) "

[git_status]
style = "yellow"
format = '([\[$all_status$ahead_behind\]]($style) )'
